function f() {
  try {
    console.log("try");
  } catch (err) {
    console.log("catch");
  } finally {
    console.log("finally");
  }
}
